version: '3'

services:

  app:
    ports:
      - "1111:80"
    build: ./docker/app
    container_name: app
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'

    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5

    container_name: phpmyadmin

    links:
      - db

    ports:
      - 1180:80

    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=user
      - PMA_PASSWORD=pass

    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
